version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "25000:25000"
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
